### ISSUE TITLE
Configuration is in UTF8 with BOM

### ISSUE THREAD

**Issue by elvince** [krakendio/krakendesigner#113]
hi,

We just loaded the docker file devopsfaith/krakendesigner and start using the designer locally.

The downloaded configuration file is in UT8 with BOM but Krakend expect a UTF8 Without BOM.
We have to convert each time the downloaded file.

We went on the live designer and the file is in UTF8 without BOM - as expected.
I notice also that the live designer have not the same design (easy catch is the download config button). I thought it was the same application that we can run locally.

Thanks for your help,

**Comment by alombarte** [comment]
Hi @elvince I missed this issue. 

I understand that with the latest releases this didn't happen. Am I correct?

**Comment by elvince** [comment]
Yes Lastest version is ok.

thanks,
